export const MenuItems=[
    {
        title:'Home',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Service',
        url:'#',
        cName:'nav-links'
    },
    {
        title:'Product',
        url:'#',
        cName:'nav-links'
    }, 
    {
        title:'Contact',
        url:'#',
        cName:'nav-links'
    }
]